### ISSUE TITLE
Descriptive message not visible in Onyphe API error

### ISSUE THREAD

**Issue by Baend** [koromodako/aionyphe#1]
Is it possible to display the descriptive message returned by the API during error 400 ?

Sample message from the API documentation : 
```
{
  "error": 3,
  "text": "Invalid API key format",
  "myip": "<redacted>",
  "status": "nok"
}
```

**Comment by koromodako** [comment]
Thank you for suggesting this enhancement !

It is possible and will be a great improvement to allow the user to understand underlying server errors if any. 

It is now available as part of release [0.2.0](https://github.com/koromodako/aionyphe/releases/tag/0.2.0) (see both 1a65bc4e62a338b021f07b7393713abb078a67aa and 26616ac95e0ea933dd5f344b2072e1e2d131598d).
